config/routes.rb
Rails.application.routes.draw do

  resources :cards
  resources :points
  resources :control_center
  resources :queries
  post 'receiver' => 'receiver#post'

  root 'queries#index'

end

app/models/card.rb
class Card < ActiveRecord::Base

end

app/models/point.rb
class Point < ActiveRecord::Base
end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  wrap_parameters format: [:json, :xml]
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def card_params
    params.require(:card).permit(:from_point_id, :to_point_id)
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.save
    redirect_to card_path(@card)
  end
end

app/controllers/control_center_controller.rb
class ControlCenterController < ApplicationController

  def index
    queries = Query.all
    cards = Card.all

    @wrong_trips = Array.new

    queries.each do |query|
      cards.each do |card|
        if card.id == query.out_card_id and card.to_point_id != query.point_id
          @wrong_trips << query
        end
        if card.id == query.in_card_id and card.from_point_id != query.point_id
          @wrong_trips << query
        end
      end
    end

  end

  def show

  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  def point_params
    params.require(:point).permit(:lat, :lon, :ttype)
  end

  def index
    @points = Point.all
  end

  def new
    @point = Point.new
  end

  def create
    @point = Point.new(point_params)
    @point.save
    redirect_to points_path
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def query_params
    params.require(:query).permit(:point_id, :in_card_id, :out_card_id, :checkin, :checkout)
  end

  def new
    @query = Query.new
  end

  def show
    @query = Query.find(params[:id])
    render json: @query
  end

  def create
    @query = Query.new(query_params)
    @query.save
    redirect_to @query
  end

  def index
    @queries = Query.all
    render json: @queries
  end

end

app/controllers/receiver_controller.rb
class ReceiverController < ApplicationController

  def post
    if Point.exists?(params[:point_id])
      @point = Point.find(params[:point_id])
     if @point.lat == params[:coords][:lat].to_f && @point.lon == params[:coords][:lon].to_f && @point.ttype == params[:ttype].to_i
        @query = Query.new
        @query.point_id = @point.id
        @query.in_card_id = params[:checkin][:card_id]
        @query.out_card_id = params[:checkout][:card_id]
        @query.checkin = params[:checkin][:timestamp]
        @query.checkout = params[:checkout][:timestamp]
        @query.save
     end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/control_center_helper.rb
module ControlCenterHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/receiver_helper.rb
module ReceiverHelper
end

app/views/cards/index.html.erb
<h1>Cards</h1>

<% @cards.each do |card| %>
        <p>Card#<%= card.id %> FROM station<%= card.from_point_id %> TO station<%= card.to_point_id %>.</p><br>
<% end %>

<%= link_to 'Add', new_card_path %><br>
<%= link_to 'Controls', controller: 'control_center' %>

app/views/cards/new.html.erb
<h1>New</h1>

<%= form_for :card, url: cards_path do |form| %>
    <p><%= form.label :from_point_id %></p>
    <%= form.text_field :from_point_id %>

    <p><%= form.label :to_point_id %></p>
    <%= form.text_field :to_point_id %>

    <br>

    <%= form.submit %>
<% end %>

app/views/cards/show.html.erb
<h1>Show</h1>

<p>ID <%= @card.id %></p>
<p>From <%= @card.from_point_id %></p>
<p>To <%= @card.to_point_id %></p>

<%= link_to 'Cards', cards_path %>

app/views/control_center/index.html.erb
<h1>ControlCenter#index</h1>

<h2>Current wrong trips</h2>

<% @wrong_trips.each do |element| %>
    <p>current point <%= element.point_id %></p>
    <p>current lat <%= Point.find(element.point_id).lat %></p>
    <p>current lon <%= Point.find(element.point_id).lon %></p>
    <p>current card_id in <%= element.in_card_id %></p>
    <p>current card_id out <%= element.out_card_id %></p>
    <p>current time in <%= element.checkin %></p>
    <p>current time out <%= element.checkout %></p>
    <br>
<% end %>
<%= link_to 'Stations', controller: 'points' %><br>
<%= link_to 'Cards', controller: 'cards' %>

app/views/control_center/show.html.erb
<h1>ControlCenter#show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uwcua</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/points/index.html.erb
<h1>Stations#index</h1>

<% @points.each do |element| %>
    <p>Station#<%= element.id %> lat: <%= element.lat %> lon: <%= element.lon %> type: <%= element.ttype %></p>
<% end %>

<%= link_to 'Add', new_point_path %><br>
<%= link_to 'Controls', controller: 'control_center' %>

app/views/points/new.html.erb
<h1>Points#new</h1>

<%= form_for @point do |form| %>
    <p><%= form.label :lat %></p>
    <%= form.text_field :lat %>

    <p><%= form.label :lon %></p>
    <%= form.text_field :lon %>

    <p><%= form.label :ttype %></p>
    <%= form.text_field :ttype %>

    <br>

    <%= form.submit %>
<% end %>

app/views/queries/index.html.erb
<h1>Queries</h1>

<% @query %>

app/views/queries/new.html.erb
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>

<h1>Queries#new</h1>

<%= form_for @query do |form| %>
    <p><%= form.label :point_id %></p>
    <%= form.text_field :point_id %>

    <p><%= form.label :in_card_id %></p>
    <%= form.text_field :in_card_id %>

    <p><%= form.label :out_card_id %></p>
    <%= form.text_field :out_card_id %>

    <p><%= form.label :checkin %></p>
    <%= form.text_field :checkin %>

    <p><%= form.label :checkout %></p>
    <%= form.text_field :checkout %>

    <br>

    <%= form.submit %>
<% end %>

<input type="button" value="Start/stop" onclick="toggle_queries()">

<script type="text/javascript">

    var timer = 0;
    var makeNewEvent = function() {

        var data = {
            point_id: Math.floor(Math.random() * 20),
            coords: {
                'lat': Math.floor(Math.random() * 180),
                'lon': Math.floor(Math.random() * 180)
            },
            ttype: 1
        };
        data['point_id'] =  data.coords['lat']*181 + data.coords['lon'] + 7;
        var in_card_id = Math.floor(Math.random() * 1000);
        var out_card_id = Math.floor(Math.random() * 1000);
        data['checkin'] = {timestamp: new Date(), card_id: in_card_id};
        data['checkout'] = {timestamp: new Date(), card_id: out_card_id};
        $.post("../receiver", data);
    };

    function toggle_queries() {
        if (timer == 0)
            timer = window.setInterval(makeNewEvent, 1000);
        else
        {
            window.clearInterval(timer);
            timer = 0;
        }
    }




</script>